# Generated by Django 4.2.3 on 2023-08-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='default-profile-picture.png', null=True, upload_to='images'),
        ),
    ]
