# Generated by Django 4.2.3 on 2023-08-08 11:32

import bg_tourism_guide.auth_app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=18, validators=[django.core.validators.MinLengthValidator(2), bg_tourism_guide.auth_app.validators.starts_with_uppercase]),
        ),
    ]
