# Generated by Django 4.2.3 on 2023-07-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_photo',
            new_name='article_image',
        ),
    ]
