# Generated by Django 4.2.3 on 2023-08-08 11:32

import bg_tourism_guide.auth_app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_article_photo_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(12), bg_tourism_guide.auth_app.validators.starts_with_uppercase]),
        ),
    ]
