# Generated by Django 4.2.3 on 2023-07-27 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Natural Site', 'NATURAL SITE'), ('History and Heritage', 'HISTORY AND HERITAGE'), ('Beach area', 'BEACH AREA'), ('Winter Sports', 'WINTER SPORTS'), ('Art and Culture', 'ART AND CULTURE'), ('Event', 'EVENT'), ('Architecture', 'ARCHITECTURE')], max_length=30)),
                ('location', models.CharField(max_length=200)),
                ('photo', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
