# Generated by Django 4.2.3 on 2023-07-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_alter_destination_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='photo',
            new_name='destination_image',
        ),
    ]
