# Generated by Django 4.2.3 on 2023-08-08 11:32

import bg_tourism_guide.auth_app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_rename_photo_destination_destination_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='destination_image',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='destination',
            name='location',
            field=models.CharField(max_length=50, validators=[bg_tourism_guide.auth_app.validators.starts_with_uppercase]),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(2), bg_tourism_guide.auth_app.validators.starts_with_uppercase]),
        ),
    ]
