# Generated by Django 4.2.3 on 2023-07-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleComment',
        ),
        migrations.RemoveField(
            model_name='destinationcomment',
            name='to_destination',
        ),
        migrations.RemoveField(
            model_name='destinationcomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='PhotoComment',
        ),
        migrations.DeleteModel(
            name='DestinationComment',
        ),
    ]
