# Generated by Django 4.2.3 on 2023-08-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time_of_publication',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
