# Generated by Django 4.2.3 on 2023-08-01 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['date_of_publication']},
        ),
    ]
