# Generated by Django 4.2.3 on 2023-08-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-date_of_publication']},
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_of_publication',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
