# Generated by Django 4.2.3 on 2023-08-08 11:32

import bg_tourism_guide.auth_app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_alter_photo_date_of_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(10), bg_tourism_guide.auth_app.validators.starts_with_uppercase]),
        ),
        migrations.AlterField(
            model_name='photo',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[bg_tourism_guide.auth_app.validators.starts_with_uppercase]),
        ),
    ]
